kind: pipeline
type: docker
name: manual-on-main

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - main
  event:
    - promote

steps:
  - name: test-main
    image: alpine
    commands:
      - echo 'Triggered manually on main'
