kind: pipeline
type: dockerMore actions
name: auto-on-staging

platform:
  os: linux
  arch: arm64

steps:
  - name: test-staging
    image: alpine
    commands:
      - echo 'Triggered automatically on staging'

