kind: pipeline
type: docker
name: auto-on-staging

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - staging
  event:
    - push

steps:
  - name: test-staging
    image: alpine
    commands:
      - echo 'Triggered automatically on staging'
---
kind: pipeline
type: docker
name: manual-on-main

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - main
  event:
    - manual

steps:
  - name: test-main
    image: alpine
    commands:
      - echo 'Triggered manually on main'
