kind: pipeline
type: docker
name: staging-automated

trigger:
  branch:
    - staging
  event:
    - push

steps:
  - name: simulate-staging-deploy
    image: alpine
    commands:
      - echo "🚀 Déploiement AUTOMATIQUE sur staging"
      - echo "Simulation construction de l'application..."
      - echo "Simulation déploiement sur serveur staging..."
      - echo "✅ Staging déployé avec succès"

---
kind: pipeline
type: docker
name: production-manual

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: build
    image: alpine
    commands:
      - echo "Build"

  - name: deploy
    image: alpine
    commands:
      - echo "Déploiement manuel"
    when:
      event: manual  
