kind: pipeline
type: docker
name: staging-automated

trigger:
  branch:
    - staging
  event:
    - push

steps:
  - name: simulate-staging-deploy
    image: alpine
    commands:
      - echo "🚀 Déploiement AUTOMATIQUE sur staging"
      - echo "Simulation construction de l'application..."
      - echo "Simulation déploiement sur serveur staging..."
      - echo "✅ Staging déployé avec succès"

---
kind: pipeline
type: docker
name: production-build

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: build
    image: alpine
    commands:
      - echo "🏗️ Construction de l'application pour production"
      - echo "Compilation des assets..."
      - echo "Tests de validation..."
      - echo "✅ Build terminé - Prêt pour déploiement"
