kind: pipeline
type: docker
name: auto-on-staging

platform:
  os: linux
  arch: arm64
  
trigger:
  branch:
    - staging
  event:
    - push
    
steps:
  - name: install-and-build-staging
    image: node:18-alpine
    commands:
      - echo "🚀 Build automatique sur staging"
      - cd test_drone
      - npm install
      - npm run lint
      - npm run build
      - echo "✅ Staging build terminé"
      
---
kind: pipeline
type: docker
name: production-build

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: install-dependencies
    image: node:18-alpine
    commands:
      - echo "📦 Installation des dépendances"
      - cd test_drone
      - npm install
      - echo "✅ Dépendances installées"

  - name: lint-and-test
    image: node:18-alpine
    commands:
      - echo "🔍 Vérification du code"
      - cd test_drone
      - npm install
      - npm run lint
      - echo "✅ Code vérifié"

  - name: build-production
    image: node:18-alpine
    commands:
      - echo "🏗️ Construction de l'application pour production"
      - cd test_drone
      - npm install
      - npm run build
      - echo "✅ Build production terminé"
    depends_on:
      - lint-and-test

---
kind: pipeline
type: docker
name: production-deploy

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - main
  event:
    - promote
  target:
    - production

steps:
  - name: deploy
    image: alpine
    commands:
      - echo "🚀 Déploiement MANUEL sur production"
      - echo "Récupération des artefacts de build..."
      - echo "Déploiement vers serveur de production..."
      - echo "✅ Production déployée avec succès"

depends_on:
  - production-build  